### ISSUE TITLE
Feature: let the user define the url of the feathers-debugger service

### ISSUE THREAD

**Issue by J3m5** [radenkovic/feathers-debugger-service#2]
I use a reverse proxy in front of my feathers server and I make it available on the `/api/` route.
So it would be nice to be able to set the path after the port or even the full URL of the server.
Thanks again!

**Comment by radenkovic** [comment]
I plan to add remote debugging the next version, so you should be able to set up the path without a problem! Thanks for the input!

**Comment by radenkovic** [comment]
@J3m5 Version 1.3 is almost there, it should allow you remote debugging, setting up the endpoint and so on, will ping you when published (I target for this Saturday). 

![](https://i.imgur.com/ViZ3aaB.png)

**Comment by radenkovic** [comment]
@J3m5 did new version help? you can set your prefix in debugger settings. so if you have reverse proxy, you can set it to
`localhost:3030/something/else` and should work.

Allowing user to change `/feathers-debugger` to something else will require changes on the chrome extension and would be harder to configure by regular users, I think it's not worth it.

**Comment by J3m5** [comment]
> did new version help? you can set your prefix in debugger settings. so if you have reverse proxy, you can set it to
localhost:3030/something/else and should work.

I didn't test it yet, I'll try it soon, this is awesome!

> Allowing user to change /feathers-debugger to something else will require changes on the chrome extension and would be harder to configure by regular users, I think it's not worth it.

I totally agree.
Thanks for the ping by the way!
