### ISSUE TITLE
Warning log spam

### ISSUE THREAD

**Issue by mrfrase3** [radenkovic/feathers-debugger-service#4]
The warning "Service feathers-debuger is not registered" fires every time the trace hook is called, this is expected when in production, but will spam the production logs.

Maybe this should only warn once?

**Comment by J3m5** [comment]
I think this warning should only run in development but some might want to run it in production.
So I would suggest to make the environment in which it run optional.

**Comment by radenkovic** [comment]
I removed it entirely in `1.3.2`, if users are having issues I will think of something better, but should be good to go.
