### ISSUE TITLE
typescript definition

### ISSUE THREAD

**Issue by bwgjoseph** [radenkovic/feathers-debugger-service#6]
Hi,

Thanks for the library, any plan to support/add type definition for this package?

**Comment by radenkovic** [comment]
:wave: @bwgjoseph I will need to check how to describe definitions for a package, but if you are comfortable, feel free to open a PR and add definitions. Thanks!

**Comment by bwgjoseph** [comment]
I have written one, but not sure if it correctly done (working for service, but not hook). I seldom do `js` project, as mostly dealt with `ts` project. Will research a little bit more and open a PR when I can soon
