### ISSUE TITLE
types was accidentally removed

### ISSUE THREAD

**Issue by bwgjoseph** [radenkovic/feathers-debugger-service#9]
Hi,

I think you accidentally removed the `types` when releasing the new version. See https://github.com/radenkovic/feathers-debugger-service/commit/2d64e595f0e485acb168ae2a7dcb248c1523c8e7#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

Not sure this is the cause that prevent typescript project from detecting the type definition file

**Comment by radenkovic** [comment]
Hey, just re-published, should be fixed!

**Comment by bwgjoseph** [comment]
Upgraded to 1.3.6 and it is working fine now. Thanks!
